version: "3"
services:
  kafka:
    image: landoop/fast-data-dev:latest
    hostname: "kafka"
    ports:
      - 2181:2181
      - 3030:3030
      - 8081-8083:8081-8083
      - 9581-9585:9581-9585
      - 9092:9092
    environment:
      - ADV_HOST=localhost
    networks:
      - kafka-network
networks:
  kafka-network:
